apiVersion: v1
kind: Secret
metadata:
  name: minio-root-credentials
  namespace: default
type: Opaque
stringData:
  rootUser: REPLACE_WITH_MINIO_ROOT_USER
  rootPassword: REPLACE_WITH_MINIO_ROOT_PASSWORD
