apiVersion: v1
kind: Secret
metadata:
  name: minio-app-credentials
  namespace: default
type: Opaque
stringData:
  saasAccessKey: REPLACE_WITH_MINIO_SAAS_ACCESS_KEY
  saasSecretKey: REPLACE_WITH_MINIO_SAAS_SECRET_KEY
  indumentariaAccessKey: REPLACE_WITH_MINIO_INDUMENTARIA_ACCESS_KEY
  indumentariaSecretKey: REPLACE_WITH_MINIO_INDUMENTARIA_SECRET_KEY
