---
# ClusterIssuer y Certificate para emitir TLS real con Let's Encrypt (HTTP-01).
# Asegurate de que los hosts apunten al Ingress y que el puerto 80 este accesible desde Internet.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: max.industry.200@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mi-nas-vaz-cert
  namespace: default
spec:
  secretName: wildcard-mydominio-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http
  dnsNames:
    - mi-nas-vaz.myqnapcloud.com
    - sistema.mi-nas-vaz.myqnapcloud.com
