apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-principal
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - indutienda.com
        - "*.indutienda.com"  # Certificado Wildcard (Requiere DNS-01, ver nota abajo)
      secretName: indutienda-wildcard-tls
  rules:
    # 1. Regla Principal (SaaS)
    - host: indutienda.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-service
                port:
                  number: 80
    - host: www.indutienda.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-service
                port:
                  number: 80

    # 2. Regla Wildcard para Tenants (Cualquier subdominio va a Indumentaria)
    - host: "*.indutienda.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indumentaria-service
                port:
                  number: 80
